# Used by "mix format"
spark_locals_without_parens = [
  adapter: 1,
  auth: 1,
  aws_sigv4: 1,
  base_url: 1,
  body: 1,
  cache: 1,
  cache_dir: 1,
  compress_body: 1,
  connect_options: 1,
  decode_body: 1,
  decode_json: 1,
  finch: 1,
  finch_private: 1,
  finch_request: 1,
  form: 1,
  form_multipart: 1,
  headers: 1,
  http_errors: 1,
  inet6: 1,
  into: 1,
  json: 1,
  max_redirects: 1,
  max_retries: 1,
  method: 1,
  params: 1,
  path_params: 1,
  path_params_style: 1,
  plug: 1,
  pool_timeout: 1,
  raw: 1,
  receive_timeout: 1,
  redirect: 1,
  redirect_trusted: 1,
  req_delete: 1,
  req_delete: 2,
  req_get: 1,
  req_get: 2,
  req_head: 1,
  req_head: 2,
  req_merge: 1,
  req_merge: 2,
  req_new: 1,
  req_new: 2,
  req_patch: 1,
  req_patch: 2,
  req_post: 1,
  req_post: 2,
  req_put: 1,
  req_put: 2,
  req_request: 1,
  req_request: 2,
  req_run: 1,
  req_run: 2,
  request: 1,
  retry: 1,
  retry_delay: 1,
  retry_log_level: 1,
  unix_socket: 1,
  url: 1,
  wait_for: 1,
  wait_for: 2
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  import_deps: [:plug, :reactor],
  plugins: [Spark.Formatter],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
